// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiO_zcgZY5t5lRYLVGujpKaHbeutL2lGs',
    appId: '1:974115324705:web:f9ba7d561bef186e54f460',
    messagingSenderId: '974115324705',
    projectId: 'balsas-entregas-ltda',
    authDomain: 'balsas-entregas-ltda.firebaseapp.com',
    storageBucket: 'balsas-entregas-ltda.firebasestorage.app',
    measurementId: 'G-B1Z344KMFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiC5vIuDciZ6dvFrSh2164nTH0uVjrxmo',
    appId: '1:974115324705:android:2a5b36b1537239c654f460',
    messagingSenderId: '974115324705',
    projectId: 'balsas-entregas-ltda',
    storageBucket: 'balsas-entregas-ltda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBBMga_54IpAB7WXCFvcGOn3TxiZRq6o8',
    appId: '1:974115324705:ios:5c87c0d7e715cb7954f460',
    messagingSenderId: '974115324705',
    projectId: 'balsas-entregas-ltda',
    storageBucket: 'balsas-entregas-ltda.firebasestorage.app',
    iosBundleId: 'com.example.balsasEntregasLtda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBBMga_54IpAB7WXCFvcGOn3TxiZRq6o8',
    appId: '1:974115324705:ios:5c87c0d7e715cb7954f460',
    messagingSenderId: '974115324705',
    projectId: 'balsas-entregas-ltda',
    storageBucket: 'balsas-entregas-ltda.firebasestorage.app',
    iosBundleId: 'com.example.balsasEntregasLtda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiO_zcgZY5t5lRYLVGujpKaHbeutL2lGs',
    appId: '1:974115324705:web:3493b835654c9e0554f460',
    messagingSenderId: '974115324705',
    projectId: 'balsas-entregas-ltda',
    authDomain: 'balsas-entregas-ltda.firebaseapp.com',
    storageBucket: 'balsas-entregas-ltda.firebasestorage.app',
    measurementId: 'G-K885XXLXD9',
  );
}
